sudo: required
dist: precise
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim
  - docker pull lacledeslan/steamcmd:linux

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-csgo --tag lacledeslan/gamesvr-csgo --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux
  - docker run -it --rm lltest/gamesvr-csgo ./ll-tests/gamesvr-csgo.sh

notifications:
  slack:
    secure: j56fJQi2Djiy85jsFP5LN+qJhq2p72HDEXa98MnANv4Fs7C97WZnybz/A0VAC6I7OAKpv0lhqZ7AcnKipqOXVjVPW4Z3pXgAV+MtSeKJW36jpajvQQc9bAdSl7QJe242Fl7/5xMw18X9InBdDQGza6MDQOV+HSQ9My5cGZGB5HcYgiVvRYMQOKoYNDhMR8q5YHkkP+JtK5mSajFhG40DI9OqhAiVNv8nN9ty1azUIhkm59XbtYTX0en7WkSsTgV8otQSFeK8p9O/7N2+jKI33uhlkxYAhVXuaYCQuDXVP73gjg2dbS0LVv7fgLRP1IjGvB/csFeHpplJdOH4KSqoYwaQwSRQQNVD7mq3JUpqUQRlwAJHaYeZjtbRIuX54olYyVNd6rJrT98a285ieMjbvQc5mi/HsvHxCJrJJaOeRlrWaCwUCSGFk7HW1AWu1BRr1pRb3Gsdoseb0HUReS3i2IzQTsbNMwW4k1+Ehep8EvjOktytv/TC4st0R2EyUcPfkgf0xqc7dV9ZL/AsExPzFO6qF56mIT/iXYbQwi8SH9XrWxt+tJwUdpYcV1bRId+nFurigJnUxTf+SksRUO3QaLV/y8g1UT14PSm4ghHwYqdFOW9tvfvIkZuCQVu/LiAI6+HhwL5p1xTFDkIkidCopog3lfXzn7bs20yYh9mWq1E=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-csgo
  on:
    branch: master

