# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'lacledeslan/gamesvr-csgo'

steps:
- script: docker pull lacledeslan/steamcmd:linux
  displayName: 'Fetch image lacledeslan/steamcmd:linux'
- script: docker pull debian:stable-slim
  displayName: 'Fetch image debian:stable-slim'
- script: docker build ./linux -t $(imageName) --no-cache --build-arg BUILDNODE=Azure;
  displayName: 'docker build'
- script: docker run -it --rm $(imageName) ./ll-tests/gamesvr-csgo.sh;
  displayName: Run self tests
