# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  contentServer: content.lacledeslan.net

jobs:
- job: Check Dependencies
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: curl --fail --head "http://"$(contentServer)"/fastDownloads/csgo/maps/de_lltest.bsp.bz2"
    displayName: 'verify content server is reachable'
- job: Build
  timeoutInMinutes: 90
  dependsOn: Check Dependencies
  steps:
  - script: docker build . -f linux.Dockerfile -t lacledeslan/gamesvr-csgo --no-cache --build-arg BUILDNODE=Azure --build-arg contentServer=$(contentServer);
    displayName: 'Docker Build'
  - script: docker run --rm lacledeslan/gamesvr-csgo ./ll-tests/gamesvr-csgo.sh;
    displayName: 'Run Self Tests'
  - script: docker login -u $(dockerUser) -p $(dockerPass)
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Log into Docker HUB'
  - script: docker push lacledeslan/gamesvr-csgo
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Push to Docker HUB'
  - script: curl -X POST  "https://hooks.microbadger.com/images/lacledeslan/gamesvr-csgo/$(microBadgerToken)"
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Update MicroBadger'
  - script: docker logout
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: 'Clean up'
